![](img/HalsHand.png)

# Agent Tutorial

![](img/LeelaZero.png)

In [1]:
import os 
import numpy as np
from ChessAgent import Agent
from ChessAgent.policy_index import policy_index
from lcztools import LeelaBoard

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
print(policy_index[:100])
print("\nLength of policy index:", len(policy_index))

['a1b1', 'a1c1', 'a1d1', 'a1e1', 'a1f1', 'a1g1', 'a1h1', 'a1a2', 'a1b2', 'a1c2', 'a1a3', 'a1b3', 'a1c3', 'a1a4', 'a1d4', 'a1a5', 'a1e5', 'a1a6', 'a1f6', 'a1a7', 'a1g7', 'a1a8', 'a1h8', 'b1a1', 'b1c1', 'b1d1', 'b1e1', 'b1f1', 'b1g1', 'b1h1', 'b1a2', 'b1b2', 'b1c2', 'b1d2', 'b1a3', 'b1b3', 'b1c3', 'b1d3', 'b1b4', 'b1e4', 'b1b5', 'b1f5', 'b1b6', 'b1g6', 'b1b7', 'b1h7', 'b1b8', 'c1a1', 'c1b1', 'c1d1', 'c1e1', 'c1f1', 'c1g1', 'c1h1', 'c1a2', 'c1b2', 'c1c2', 'c1d2', 'c1e2', 'c1a3', 'c1b3', 'c1c3', 'c1d3', 'c1e3', 'c1c4', 'c1f4', 'c1c5', 'c1g5', 'c1c6', 'c1h6', 'c1c7', 'c1c8', 'd1a1', 'd1b1', 'd1c1', 'd1e1', 'd1f1', 'd1g1', 'd1h1', 'd1b2', 'd1c2', 'd1d2', 'd1e2', 'd1f2', 'd1b3', 'd1c3', 'd1d3', 'd1e3', 'd1f3', 'd1a4', 'd1d4', 'd1g4', 'd1d5', 'd1h5', 'd1d6', 'd1d7', 'd1d8', 'e1a1', 'e1b1', 'e1c1']

Length of policy index: 1858


In [3]:
agent = Agent()
board = LeelaBoard()

In [4]:
print(board)

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
Turn: White


### Model Input

The model input is a binary matrix that encodes all the information that the agent needs to determine the best move to make. 

In [5]:
input_planes = board.lcz_features()

print('Shape:', input_planes.shape)
print('Max: {}, Min: {}'.format(np.max(input_planes), np.min(input_planes)))

Shape: (112, 8, 8)
Max: 1, Min: 0


### Model Output

The model output is a probability distribution over all the moves. 

In [6]:
policy = agent.get_policy(board)
print(policy)

[0.0003677  0.00051452 0.00067407 ... 0.00060703 0.00056749 0.0005363 ]


In [7]:
len(policy)

1858

In [8]:
argmax = np.argmax(policy)
argmax

293

In [9]:
best_move = policy_index[argmax]
print(best_move)

d2d4


In [10]:
agent._evaluate(board)

OrderedDict([('d2d4', 0.29889076948165894),
             ('g1f3', 0.2022378295660019),
             ('c2c4', 0.12169891595840454),
             ('e2e4', 0.09218282997608185),
             ('g2g3', 0.055393755435943604),
             ('e2e3', 0.045928746461868286),
             ('c2c3', 0.02649873122572899),
             ('b1c3', 0.023393454030156136),
             ('h2h3', 0.022247301414608955),
             ('b2b3', 0.022095954045653343),
             ('a2a3', 0.021670717746019363),
             ('d2d3', 0.021540973335504532),
             ('a2a4', 0.010906515643000603),
             ('b2b4', 0.008047505281865597),
             ('f2f4', 0.0069420225918293),
             ('b1a3', 0.004659567028284073),
             ('h2h4', 0.0045971982181072235),
             ('g1h3', 0.004334136378020048),
             ('f2f3', 0.0036809640005230904),
             ('g2g4', 0.0030521415174007416)])

In [11]:
board.push_uci(best_move)
print(board)

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R
Turn: Black


In [12]:
while board.is_game_over() == False: 

    best_move = agent.get_move(board)
    board.push_uci(best_move)
    print(board)
    print('\n\n')

r n b q k b . r
p p p p p p p p
. . . . . n . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R
Turn: White



r n b q k b . r
p p p p p p p p
. . . . . n . .
. . . . . . . .
. . . P . . . .
. . . . . N . .
P P P . P P P P
R N B Q K B . R
Turn: Black



r n b q k b . r
p p p p . p p p
. . . . p n . .
. . . . . . . .
. . . P . . . .
. . . . . N . .
P P P . P P P P
R N B Q K B . R
Turn: White



r n b q k b . r
p p p p . p p p
. . . . p n . .
. . . . . . . .
. . P P . . . .
. . . . . N . .
P P . . P P P P
R N B Q K B . R
Turn: Black



r n b q k b . r
p p p . . p p p
. . . . p n . .
. . . p . . . .
. . P P . . . .
. . . . . N . .
P P . . P P P P
R N B Q K B . R
Turn: White



r n b q k b . r
p p p . . p p p
. . . . p n . .
. . . p . . . .
. . P P . . . .
. . N . . N . .
P P . . P P P P
R . B Q K B . R
Turn: Black



r n b q k b . r
p p p . . p p p
. . . . p . . .
. . . p . . . .
. . P P n . . .
. . N . . N . .
P P . . P P P P
R . B Q K B . R
Turn: White




r . . r . . k .
. . R . . . . .
. . . . . . B B
p . p . . p . .
. . . . . . . .
. b . . . P P .
. P . . . . . P
. . . . R . K .
Turn: Black



r . . r . . k .
. . R . . . . .
. . . . . . B B
p . p . . . . .
. . . . . p . .
. b . . . P P .
. P . . . . . P
. . . . R . K .
Turn: White



r . . r . . k .
. . R . R . . .
. . . . . . B B
p . p . . . . .
. . . . . p . .
. b . . . P P .
. P . . . . . P
. . . . . . K .
Turn: Black



r . . . . . k .
. . R . R . . .
. . . . . . B B
p . p . . . . .
. . . . . p . .
. b . . . P P .
. P . . . . . P
. . . r . . K .
Turn: White



r . . . . . k .
. . R . . . . .
. . . . . . B B
p . p . . . . .
. . . . . p . .
. b . . . P P .
. P . . . . . P
. . . r R . K .
Turn: Black



r . . . . . k .
. . R . . . . .
. . . . . . B B
p . . . . . . .
. . p . . p . .
. b . . . P P .
. P . . . . . P
. . . r R . K .
Turn: White



r . . . . . k .
. . R . . . . .
. . . . . . B B
p . . . . . . .
. . p . . p . .
. b . . . P P .
. P . . . . . P
. . . R . . K .
Turn: Black


