# ChessMachine

![](img/HalsHand.png)

In [1]:
import os 
import numpy as np

### Agent 

![](img/LeelaZero.png)

In [2]:
from Agent.keras_net import KerasNet
from Agent.policy_index import policy_index
from lcztools import LeelaBoard

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
net = KerasNet()
board = LeelaBoard()

In [4]:
print(board)

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
Turn: White


### Model Input

In [5]:
input_planes = board.lcz_features()
print('Shape:', input_planes.shape)
print('Max: {}, Min: {}'.format(np.max(input_planes), np.min(input_planes)))

Shape: (112, 8, 8)
Max: 1, Min: 0


### Model Output

In [1]:
policy = net.get_policy(board)
print(policy)

NameError: name 'net' is not defined

In [10]:
len(policy)

1858

In [12]:
argmax = np.argmax(policy)
argmax

293

In [13]:
policy_index

['a1b1',
 'a1c1',
 'a1d1',
 'a1e1',
 'a1f1',
 'a1g1',
 'a1h1',
 'a1a2',
 'a1b2',
 'a1c2',
 'a1a3',
 'a1b3',
 'a1c3',
 'a1a4',
 'a1d4',
 'a1a5',
 'a1e5',
 'a1a6',
 'a1f6',
 'a1a7',
 'a1g7',
 'a1a8',
 'a1h8',
 'b1a1',
 'b1c1',
 'b1d1',
 'b1e1',
 'b1f1',
 'b1g1',
 'b1h1',
 'b1a2',
 'b1b2',
 'b1c2',
 'b1d2',
 'b1a3',
 'b1b3',
 'b1c3',
 'b1d3',
 'b1b4',
 'b1e4',
 'b1b5',
 'b1f5',
 'b1b6',
 'b1g6',
 'b1b7',
 'b1h7',
 'b1b8',
 'c1a1',
 'c1b1',
 'c1d1',
 'c1e1',
 'c1f1',
 'c1g1',
 'c1h1',
 'c1a2',
 'c1b2',
 'c1c2',
 'c1d2',
 'c1e2',
 'c1a3',
 'c1b3',
 'c1c3',
 'c1d3',
 'c1e3',
 'c1c4',
 'c1f4',
 'c1c5',
 'c1g5',
 'c1c6',
 'c1h6',
 'c1c7',
 'c1c8',
 'd1a1',
 'd1b1',
 'd1c1',
 'd1e1',
 'd1f1',
 'd1g1',
 'd1h1',
 'd1b2',
 'd1c2',
 'd1d2',
 'd1e2',
 'd1f2',
 'd1b3',
 'd1c3',
 'd1d3',
 'd1e3',
 'd1f3',
 'd1a4',
 'd1d4',
 'd1g4',
 'd1d5',
 'd1h5',
 'd1d6',
 'd1d7',
 'd1d8',
 'e1a1',
 'e1b1',
 'e1c1',
 'e1d1',
 'e1f1',
 'e1g1',
 'e1h1',
 'e1c2',
 'e1d2',
 'e1e2',
 'e1f2',
 'e1g2',
 'e1c3',
 'e1d3',
 

In [14]:
policy_index[argmax]

'd2d4'

In [15]:
net._evaluate(board)

OrderedDict([('d2d4', 0.29889070987701416),
             ('g1f3', 0.20223784446716309),
             ('c2c4', 0.12169887125492096),
             ('e2e4', 0.09218282997608185),
             ('g2g3', 0.0553937703371048),
             ('e2e3', 0.045928727835416794),
             ('c2c3', 0.026498733088374138),
             ('b1c3', 0.02339346334338188),
             ('h2h3', 0.022247303277254105),
             ('b2b3', 0.022095955908298492),
             ('a2a3', 0.021670708432793617),
             ('d2d3', 0.02154098078608513),
             ('a2a4', 0.01090650912374258),
             ('b2b4', 0.008047501556575298),
             ('f2f4', 0.006942023988813162),
             ('b1a3', 0.004659565631300211),
             ('h2h4', 0.004597201943397522),
             ('g1h3', 0.004334137309342623),
             ('f2f3', 0.003680964931845665),
             ('g2g4', 0.0030521440785378218)])

In [2]:
net.get_move(board)

NameError: name 'net' is not defined

## Vision

![](img/Vision.png)